export enum ModelerActions {
  cut = 'cut',
  copy = 'copy',
  paste = 'paste',
  find = 'find',
  undo = 'undo',
  canUndo = 'canUndo',
  redo = 'redo',
  canRedo = 'canRedo',
  setColor = 'setColor',
  handTool = 'handTool',
  lassoTool = 'lassoTool',
  spaceTool = 'spaceTool',
  globalConnectTool = 'globalConnectTool',
  directEditing = 'directEditing',
  selectElements = 'selectElements',
  removeSelection = 'removeSelection',
  zoom = 'zoom',
  resetZoom = 'resetZoom',
  zoomIn = 'zoomIn',
  zoomOut = 'zoomOut',
  zoomToFit = 'zoomToFit',
  distributeElements = 'distributeElements',
  alignElements = 'alignElements',
  hasSelection = 'hasSelection',
  showMinimap = 'showMinimap',
  hideMinimap = 'hideMinimap',
}
